Rails.application.routes.draw do
  get "books/index"
  get "books/show"
  # Authentication routes (generated by Rails)
  resource :session, only: [:new, :create, :destroy] # Handles login/logout
  resources :passwords, param: :token, only: [:new, :create, :edit, :update] # Handles password reset

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Application routes
  root "books#index" # Set the homepage to the books index page

  # Book routes
  resources :books, only: [:index, :show] do
    # Borrowing routes nested under books
    resources :borrowings, only: [:create]
  end

  # Borrowing routes (for returning books)
  resources :borrowings, only: [:update]

  # User profile route
  resource :user, only: [:show] # Shows the current user's profile and borrowed books
end